More aggressive sanitizer diagnostics
clostra/newnode pull request #30
Opened 2017-05-26 10:41 UTC by inetic

2017-05-26 17:44 UTC, shalunov commented
There is now a sanitizer failure on Mac, but not Linux. Any ideas what's going on?

2017-05-26 18:01 UTC, inetic commented
Some of the sanitizer options are not available on with the clang version on ci/linux and some of them are not available on ci/mac. The good news is that I can reproduce that error locally. I'll get back to it on Monday.

2017-05-26 18:38 UTC, shalunov commented
Thank you!

2017-05-29 20:54 UTC, shalunov requested changes

2017-05-29 20:54 UTC, shalunov commented on dht.cpp
> +    buf[fsize] = '\0'; // The BencEntity::Parse function expects this to be a null terminated string.
How did this work before?

2017-05-29 20:54 UTC, shalunov commented on injector_helper.c
> +static bool fd_local_info(int fd, char *addr, size_t addrlen, uint16_t *port)
What does this function do? Where does it change addr? What does addr represent?

2017-05-29 20:54 UTC, shalunov commented on build.sh
> -echo "int main() {}"|clang -x c - -lrt 2>/dev/null && LRT="-lrt"
Why move these lines?

2017-05-29 20:55 UTC, shalunov commented
Also, do you understand the reported coverage changes?

2017-05-30 06:42 UTC, inetic commented on dht.cpp
> +    buf[fsize] = '\0'; // The BencEntity::Parse function expects this to be a null terminated string.
While the dht.dat file was being read, the last function that was called to read it was [BencEntity::ParseNum](https://github.com/bittorrent/libbtutils/blob/d39069c55c463a1b5ff51dad04ac2f40de6e3060/src/bencoding.cpp#L544). Note that the function doesn't take as an argument the end boundary of the buffer and so if the string wasn't null terminated it was reading past that boundary.

2017-05-30 06:53 UTC, shalunov commented on dht.cpp
> +    buf[fsize] = '\0'; // The BencEntity::Parse function expects this to be a null terminated string.
👍

2017-05-30 06:58 UTC, inetic commented on injector_helper.c
> +static bool fd_local_info(int fd, char *addr, size_t addrlen, uint16_t *port)
> What does this function do?

It just "returns" the local address and port of the socket represented by that `fd`. The code is pretty much a copy/paste from [here](https://github.com/nmathewson/Libevent/blob/2773a5ed5e75540d43500e054581ea1fab2132ac/sample/http-server.c#L377).

> Where does it change addr?

[Here](https://github.com/clostra/dcdn/pull/30/files/59b580a4c034eec858d6b8dd4b0cf529c4a0894d#diff-e90daa1466feff8e719bfc57e56fcc95R116).
> What does addr represent?

The local address of the socket represented by the `fd`. Most likely "0.0.0.0". This string is only used when printing the line `listening on UDP:0.0.0.0:5678`. Getting the local port has more significance though.

2017-05-30 07:03 UTC, shalunov commented on injector_helper.c
> +static bool fd_local_info(int fd, char *addr, size_t addrlen, uint16_t *port)
👍

2017-05-30 07:04 UTC, shalunov commented on injector_helper.c
> +static bool fd_local_info(int fd, char *addr, size_t addrlen, uint16_t *port)
(In an ideal world, we'd use the normal return convention, but probably not worth changing right now.)

2017-05-30 07:05 UTC, inetic commented on build.sh
> -echo "int main() {}"|clang -x c - -lrt 2>/dev/null && LRT="-lrt"
[This](https://github.com/clostra/dcdn/pull/30/files/d3f8f50239abde0fccf9c345ba6415ca925fd465#diff-0b83f9dedf40d7356e5ca147a077acb4R34) new line of code, and the one below it, had to go _before_ [this one](https://github.com/clostra/dcdn/pull/30/files/d3f8f50239abde0fccf9c345ba6415ca925fd465#diff-0b83f9dedf40d7356e5ca147a077acb4R42). I thought it makes sense to have all the `dependency checking code` together, so I moved the rest with it.

2017-05-30 07:07 UTC, shalunov commented on build.sh
> -echo "int main() {}"|clang -x c - -lrt 2>/dev/null && LRT="-lrt"
I'd rather minimize moving code like that, since we have a pretty big merge ahead of us. Could you change this so it only adds lines, please?

2017-05-30 07:38 UTC, merged