Coverage increase by utilizing the CONNECT method
clostra/newnode pull request #48
Opened 2017-06-07 15:49 UTC by inetic

2017-06-07 16:25 UTC, inetic commented
Pls, don't merge yet. I'm not sure I understand the coverage results.

2017-06-07 19:04 UTC, shalunov requested changes

2017-06-07 19:04 UTC, shalunov commented on injector.c
> +    fprintf(stderr, "scheme:%s\n", scheme);
Could you avoid changes to injector.c?

2017-06-07 19:04 UTC, shalunov commented on test.sh
> +GOOGLE=172.217.7.142
Why the IP? Google.com and other Google domains resolve is complicated source- and time-dependent ways, sometimes through CNAMEs. If you want google.com, I'd use that directly.

2017-06-07 19:04 UTC, shalunov commented on test.sh
> +    if ! do_curl $proxy_tcp_port $GOOGLE $HTTP_OK; then
`s/\$GOOGLE/google.com/`?

2017-06-07 19:04 UTC, shalunov commented on test.sh
> +trap cleanup SIGINT SIGTERM EXIT
Good idea. I had things left hanging after ^C.

2017-06-07 21:17 UTC, inetic commented on injector.c
> +    fprintf(stderr, "scheme:%s\n", scheme);
Yes, this slipped in while debugging, will remove.

2017-06-07 21:17 UTC, inetic commented on test.sh
> +GOOGLE=172.217.7.142
Also part of debugging, will remove.

2017-06-07 21:19 UTC, inetic commented on test.sh
> +trap cleanup SIGINT SIGTERM EXIT
Yes, or after a test failed, was quite annoying.

2017-06-07 21:19 UTC, inetic commented on test.sh
> +    if ! do_curl $proxy_tcp_port $GOOGLE $HTTP_OK; then
yip

2017-06-08 11:41 UTC, inetic commented
OK, this one is ready to be merged now. (resolves #44)

2017-06-08 20:50 UTC, shalunov approved these changes

2017-06-08 20:50 UTC, merged