New UI for NewNode VPN for Android
clostra/newnode pull request #99
Opened 2021-05-26 14:13 UTC by IvanSeleznevSpb

2021-05-31 16:34 UTC, ghazel requested changes

2021-05-31 16:34 UTC, ghazel commented on android/vpn/app/src/main/java/com/clostra/newnode/vpn/statistics/StatisticsFragment.java
> +    private String dateVolumeToString (double bytes) {
`android.text.format.Formatter.formatShortFileSize` does a great job at this.

2021-05-31 16:34 UTC, ghazel commented on android/vpn/app/src/main/java/com/clostra/newnode/vpn/VpnService.java
> +
Was the change in this file necessary?

2021-06-01 20:11 UTC, IvanSeleznevSpb commented on android/vpn/app/src/main/java/com/clostra/newnode/vpn/statistics/StatisticsFragment.java
> +    private String dateVolumeToString (double bytes) {
Excellent. Thanks for the advice.

2021-06-01 20:11 UTC, IvanSeleznevSpb commented on android/vpn/app/src/main/java/com/clostra/newnode/vpn/VpnService.java
> +
I'm sorry. This is accidental. Revert.

2021-06-02 17:38 UTC, ghazel approved these changes

2021-06-02 17:51 UTC, merged